### ISSUE TITLE
Suggested Improvements for a Professional Look

### ISSUE THREAD

**Issue by Libs100** [yuliaerk/yuliaerk.github.io#1]
Hi Yulia, 

I saw your site and loved the cute pig compilation!

I have a small suggestion to improve the layout and make the content look more professional. You might consider adding a bit of space between the information about your PhD research and the personal details, like your Aliyah story. 
Adding a link to your lab would be a great touch for easy access as well.

Hope this helps! 😊

**Comment by Aish16032001** [comment]
Hii Yulia,
I liked your website. It's to point. The only thing which I suggest is that you can more details about your research to make it beneficial for people involved in research. For ex- adding your masters project, or any rotation work, as well as giving rough idea of your PhD research will also be great.
Thankyou

**Comment by yuliaerk** [comment]
Hey,
thanks a lot! Please check the new changes now :)

**Comment by yuliaerk** [comment]
@hadarklimovski
