### ISSUE TITLE
Regarding suggestion

### ISSUE THREAD

**Issue by Aish16032001** [yuliaerk/yuliaerk.github.io#2]
Hii Yulia,
I liked your website. It's to point. The only thing which I suggest is that you can add more details about your research to make it beneficial for people involved in research. For ex- adding your masters project, or any rotation work will also be great.
Thankyou

**Comment by Aish16032001** [comment]
@liroh99

**Comment by yuliaerk** [comment]
@Aish16032001 hi, check a new version, please. Have a nice evening!

**Comment by yuliaerk** [comment]
@hadarklimovski

**Comment by Aish16032001** [comment]
looks great
